spring:
    application:
        name: name-of-the-microservice01
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    healthcheck:
        enabled: true
server:
    port: 8762